# Generated by Django 3.2.5 on 2021-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='description',
            new_name='specifications',
        ),
        migrations.AlterField(
            model_name='phone',
            name='rating',
            field=models.FloatField(),
        ),
    ]
